name: Daily Commit

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update daily file
        run: |
          echo "Last updated: $(date)" > daily.txt

      - name: Commit changes
        run: |
          git config user.name "Pratiti-paul"
          git config user.email "pratiti.paul2024@nst.rishihood.edu.in"
          
          git add daily.txt

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: daily update"
            git push
          fi
